# Default values for openmrs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  defaultStorageClass: "gp2"

ingress:
  enabled: false

service:
  type: NodePort
  port: 80

openmrs-backend:
  infinispan:
    clustered: true
    bind_port: 7800

  db:
    hostname: ""

  galera:
    enabled: false
    rootUser:
      password: Root123
    db:
      name: openmrs
      user: openmrs
      password: OpenMRS123

  mariadb:
    enabled: true
    auth:
      rootPassword: Root123
      database: openmrs
      username: openmrs
      password: OpenMRS123

