# Default values for openmrs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  defaultStorageClass: "gp2"

openmrs-backend:
  nameOverride: "backend"

  infinispan:
    clustered: true
    bind_port: 7800

  db:
    hostname: ""

  galera:
    enabled: false
    rootUser:
      password: Root123
    db:
      name: openmrs
      user: openmrs
      password: OpenMRS123

  mariadb:
    enabled: true
    auth:
      rootPassword: Root123
      database: openmrs
      username: openmrs
      password: OpenMRS123

openmrs-frontend:
  nameOverride: "frontend"
