apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmrs-tenant.backend.fullname" . }}
  labels:
    {{- include "openmrs-tenant.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  OMRS_DB_USERNAME: {{ required "backend.db.user is required" .Values.backend.db.user | quote }}
  OMRS_DB_PASSWORD: {{ required "backend.db.password is required" .Values.backend.db.password | quote }}
