apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmrs-tenant.frontend.fullname" . }}
  labels:
    {{- include "openmrs-tenant.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openmrs-tenant.frontend.selectorLabels" . | nindent 4 }}
