apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openmrs-backend.fullname" . }}
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
data:
  {{- if .Values.mariadb.enabled }}
  OMRS_DB: "mariadb"
  OMRS_DB_NAME: {{ .Values.mariadb.auth.database | default "openmrs" | quote }}
  {{- if .Values.mariadb.galera }}
  OMRS_DB_HOSTNAME: "{{ .Release.Name }}-mariadb"
  {{- else }}
  OMRS_DB_HOSTNAME: "{{ .Release.Name }}-mariadb-primary"
  {{- end }}
  {{- else }}
  {{- if .Values.db.url }}
  OMRS_DB_URL: {{ .Values.db.url | quote }}
  {{- else }}
  OMRS_DB_HOSTNAME: {{ .Values.db.hostname | quote }}
  OMRS_DB_PORT: {{ .Values.db.port | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.elasticsearch.enabled }}
  OMRS_SEARCH: "elasticsearch"
  OMRS_SEARCH_ES_URIS: {{ include "openmrs-elasticsearch.url" . }}
  {{- else if .Values.elasticsearch.uris }}
  OMRS_SEARCH: "elasticsearch"
  OMRS_SEARCH_ES_URIS: {{ .Values.elasticsearch.uris | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  storage.type: "s3"
  storage.s3.region: "us-east-1"
  storage.s3.endpoint: {{ include "openmrs-minio.url" . }}
  storage.s3.forcePathStyle: "true"
  {{- end }}
  {{- if .Values.infinispan.clustered }}
  cache.type: "cluster"
  cache.stack: "kubernetes"
  jgroups.dns.query: '{{ include "openmrs-backend.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
  jgroups.bind.port: {{ .Values.infinispan.bind_port | quote }}
  {{- else }}
  cache.type: "local"
  {{- end }}