{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "openmrs-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/openmrs/`)
      kind: Rule
      services:
        - name: {{ include "openmrs-backend.fullname" . }}-sticky
          kind: TraefikService
{{- end }}
