{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmrs-backend.fullname" . }}-mariadb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.mariadb.auth.rootPassword | default "Root123" | quote }}
  user-password: {{ .Values.mariadb.auth.password | default "OpenMRS123" | quote }}
{{- end }}
