apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmrs-backend.fullname" . }}
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.infinispan.clustered }}
    - port: {{ .Values.infinispan.bind_port }}
      targetPort: {{ .Values.infinispan.bind_port }}
      protocol: TCP
      name: infinispan-hibernate
    - port: {{ add .Values.infinispan.bind_port 1 }}
      targetPort: {{ add .Values.infinispan.bind_port 1 }}
      protocol: TCP
      name: infinispan-api
    {{ end }}
  selector:
    {{- include "openmrs-backend.selectorLabels" . | nindent 4 }}
