{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openmrs-backend.serviceAccountName" . }}
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openmrs-backend.serviceAccountName" . }}-statefulset-reader
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openmrs-backend.serviceAccountName" . }}-statefulset-reader-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "openmrs-backend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "openmrs-backend.serviceAccountName" . }}-statefulset-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}