{{- if .Values.traefikService.enabled }}
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: {{ include "openmrs-backend.fullname" . }}-sticky
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
spec:
  weighted:
    services:
      - name: {{ include "openmrs-backend.fullname" . }}
        port: {{ .Values.service.port | default 8080 }}
        weight: 1
        sticky:
          cookie:
            name: openmrs_session
            secure: false
            httpOnly: true
{{- end }}
