global:
  defaultStorageClass: standard
openmrs-backend:
  image:
    repository: openmrs/openmrs-reference-application-3-backend
    tag: nightly-0-core-2.8
    pullPolicy: IfNotPresent #IfNotPresent / Always
  replicaCount: 2
  startupProbe:
    httpGet:
      path: /openmrs/health/started
      port: 8080
    initialDelaySeconds: 20
    failureThreshold: 360
    timeoutSeconds: 1
    periodSeconds: 10
  gateway:
    enabled: true
    parentRefs:
      namespace: openmrs-system
  infinispan:
    clustered: true
  monitoring:
    enabled: true
  grafana:
    ingress:
      enabled: false
    route: {}
    httpRoute:
      enabled: true
      hostnames:
        - localhost
      path: /grafana
    grafana.ini:
      server:
        domain: localhost
        root_url: "http://localhost:8080/grafana"
        serve_from_sub_path: true
      dashboards:
        default_home_dashboard_path: /var/lib/grafana/dashboards/default/logs-dashboard.json
  mariadb:
    enabled: true
  elasticsearch:
    enabled: true

  elasticsearch-eck:
    version: "8.15.3"
    image: openmrs/openmrs-contrib-elasticsearch:8.15.3
    nodeSets:
      - name: default
        count: 1
        config:
          node.roles:
            - master
            - data
            - ingest
          node.store.allow_mmap: false
        
        podTemplate:
          spec:
            containers:
              - name: elasticsearch
                resources:
                  requests:
                    cpu: 500m
                    memory: "2Gi"
                    ephemeral-storage: 2Gi
                  limits:
                    cpu: 750m
                    memory: "2Gi"
                    ephemeral-storage: 10Gi

  seaweedfs:
    enabled: true
    global:
      seaweedfs:
        enableSecurity: false
    master:
      replicas: 3
    volume:
      enabled: true
      replicas: 3
      dataDirs:
        - name: data
          type: "persistentVolumeClaim"
          storageClass: "standard"
          size: "8Gi"
          maxVolumes: 0
    filer:
      enabled: true
      replicas: 3
      extraEnvironmentVars:
        WEED_MYSQL_ENABLED: "true"
        WEED_MYSQL_HOSTNAME: "{{ .Release.Name }}-mariadb"
        WEED_MYSQL_DATABASE: "openmrs"
        WEED_MYSQL_USERNAME: "openmrs"
        WEED_LEVELDB2_ENABLED: "false"
      secretExtraEnvironmentVars:
        WEED_MYSQL_PASSWORD:
          secretKeyRef:
            name: "openmrs-backend-mariadb-secret"
            key: user-password
    admin:
      enabled: true
      urlPrefix: /seaweedfs-admin
      ingress:
        enabled: false
      httpRoute:
        enabled: true
      secret:
        adminPassword: Admin123
    s3:
      enabled: true
      replicas: 2
      enableAuth: true
      credentials:
        admin:
          accessKey: "openmrs"
          secretKey: "OpenMRS123"
      createBuckets:
        - name: openmrs
openmrs-frontend:
  gateway:
    enabled: true
    parentRefs:
      namespace: openmrs-system
  rootRedirect:
    enabled: true
  image:
    repository: openmrs/openmrs-reference-application-3-frontend
    tag: nightly-0-core-2.8
    pullPolicy: IfNotPresent #IfNotPresent / Always