global:
  defaultStorageClass: standard
traefik-gateway:
  traefik:
    ports:
      web:
        hostPort: 80
mariadb:
  auth:
    rootPassword: Root123
    replicationPassword: Replicate123
    database: openmrs
    username: openmrs
    password: OpenMRS123