name: Release Charts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Chart version (e.g. 1.2.1)"
        required: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.2

      - name: Add Helm Repositories
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts

      - name: Set Chart Version
        if: github.event_name == 'workflow_dispatch'
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          # Update version in Chart.yaml files
          sed -i "s/^version: .*/version: $VERSION/" helm/openmrs/Chart.yaml
          sed -i "s/^version: .*/version: $VERSION/" helm/openmrs-backend/Chart.yaml
          sed -i "s/^version: .*/version: $VERSION/" helm/openmrs-frontend/Chart.yaml
          # Update dependency versions in main chart
          sed -i "/name: openmrs-backend/,/version:/ s/version: .*/version: $VERSION/" helm/openmrs/Chart.yaml
          sed -i "/name: openmrs-frontend/,/version:/ s/version: .*/version: $VERSION/" helm/openmrs/Chart.yaml

      - name: Build dependencies
        run: |
          helm dependency update helm/openmrs-backend
          helm dependency update helm/openmrs-frontend
          helm dependency update helm/openmrs

      - name: Commit and Push Changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git add helm/**/Chart.yaml helm/**/Chart.lock
          git commit -m "Bump chart versions to ${{ github.event.inputs.version }}"
          git push

      - name: Create Tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag "v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"

      - name: Update Chart.yaml dependencies
        run: |
          # Replace local file paths with the GitHub Pages URL for the release
          REPO_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          sed -i "s|repository: \"file://../openmrs-backend\"|repository: \"$REPO_URL\"|g" helm/openmrs/Chart.yaml
          sed -i "s|repository: \"file://../openmrs-frontend\"|repository: \"$REPO_URL\"|g" helm/openmrs/Chart.yaml
          # Remove Chart.lock because it is now out of sync with Chart.yaml (remote vs local)
          rm helm/openmrs/Chart.lock

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"